# Generated by Django 5.0.1 on 2024-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('price_usd', models.IntegerField()),
                ('odometer', models.IntegerField()),
                ('username', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('images_count', models.IntegerField()),
                ('car_number', models.CharField(max_length=255)),
                ('car_vin', models.CharField(max_length=255)),
                ('datatime_found', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
